#!/bin/bash

# Example Usgage
#
#   ./send_kafka location-topic 7c451c 11300.0 -33.766852,151.167412
#   ./send_kafka ident-topic 7c451c QJE1726


if [ -z ${HOST_IP} ]; then
  HOST_IP=192.168.1.129
fi

REST_URL=http://${HOST_IP}:8082

echo "REST_URL : ${REST_URL}"

ICAO=`echo ${2} | tr '[:lower:]' '[:upper:]'`

if [  $# == 4 -a ${1} == "location-topic" ]; then
  echo ${1} ${ICAO} ${3} ${4}
  DATA='{"value_schema": "{\"type\": \"record\", \"name\": \"com.example.ident\", \"fields\": '
  DATA+='[{\"name\": \"ico\", \"type\": \"string\"},{\"name\": \"height\", \"type\": \"string\"},{\"name\": \"location\", \"type\": \"string\"}]}", '
  DATA+='"records": [{"value": {"ico": "'${ICAO}'", "height": "'${3}'", "location": "'${4}'"}}]}'

elif [ $# == 3 -a ${1} == "ident-topic" ]; then
  echo ${1} ${2} ${3} 
  DATA='{"value_schema": "{\"type\": \"record\", \"name\": \"com.example.ident\", \"fields\": '
  DATA+='[{\"name\": \"ico\", \"type\": \"string\"},{\"name\": \"indentification\", \"type\": \"string\"}]}", '
  DATA+='"records": [{"value": {"ico": "'${ICAO}'", "indentification": "'${3}'"}}]}'

else
  echo "Usage ${0} :  [location-topic ico height location] [ident-topic identification]  "
  exit 1
fi

KAFKA_TOPIC=${1}


curl -s -X POST -H "Content-Type: application/vnd.kafka.avro.v2+json" \
   -H "Accept: application/vnd.kafka.v2+json" \
   --data "${DATA}" \
   "${REST_URL}/topics/${KAFKA_TOPIC}" 

echo
