#!/bin/bash

curl -Xput "http://elasticsearch:9200/locationtable" -H 'Content-Type: application/json' -d'
{
    "mappings": {
      "type.name=kafkaconnect": {
        "properties": {
          "EVENTS": {
            "type": "long"
          },
          "EVENT_TS": {
            "type": "date"
          },
          "HEIGHT": {
            "type": "float"
          },
          "ICO": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "LOCATION": {
            "type": "geo_point"
          }
        }
      }
    }
}'

echo
