#!/bin/bash

topic_to_elastic () {
  table_name=$1
  TABLE_NAME=`echo $table_name | tr '[a-z]' '[A-Z]'`

  curl -X "POST" "http://localhost:8083/connectors/" \
     -H "Content-Type: application/json" \
     -d $'{
  "name": "es_sink_'$TABLE_NAME'",
  "config": {
    "schema.ignore": "true",
    "topics": "'$TABLE_NAME'",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter.schemas.enable": false,
    "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
    "key.ignore": "true",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "type.name": "type.name=kafkaconnect",
    "topic.index.map": "'$TABLE_NAME':'$table_name'",
    "connection.url": "http://elasticsearch:9200",
    "transforms": "FilterNulls,ExtractTimestamp",
    "transforms.FilterNulls.type": "io.confluent.transforms.NullFilter",
    "transforms.ExtractTimestamp.type": "org.apache.kafka.connect.transforms.InsertField$Value",
    "transforms.ExtractTimestamp.timestamp.field" : "EVENT_TS"
  }
}' 

  echo
}


topic_to_elastic locationtable
