#!/usr/bin/env bash

unset http_proxy
unset https_proxy
export http_proxy
export https_proxy

HOST=elasticsearch

echo "Loading Elastic Dynamic Templates"

curl -XDELETE "http://${HOST}:9200/_template/kafkaconnect/"
echo
echo

curl -XPUT "http://${HOST}:9200/_template/kafkaconnect/" -H 'Content-Type: application/json' -d'
{
  "template": "*",
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 0
  },
  "mappings": {
    "_default_": {
      "dynamic_templates": [
        {
          "dates": {
            "match": "EVENT_TS",
            "mapping": {
              "type": "date"
            }
          }
        },
        {
          "heights": {
            "match": "HEIGHT",
            "mapping": {
              "type": "float"
            }
          }
        },
        {
          "locations": {
            "match": "LOCATION",
            "mapping": {
              "type": "geo_point"
            }
          }
        }
      ]
    }
  }
}'

echo
